name = "d1-sveltekit-repro"
compatibility_date = "2022-12-22"

account_id = "ddc432a56044bef92b27a42975d4c42e"
main = "./.svelte-kit/cloudflare/_worker.js"

[site]
bucket = "./.svelte-kit/cloudflare"

[build]
command = "npm run build"

workers_dev = true

kv_namespaces = [
    { binding = "KV", id = "ec161eca395a4381a28dfa1943c15eb7" }
]

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "d1-sveltekit-repro-db"
database_id = "c88ba74e-338b-45d5-aaa3-961c8b4dc585"
